# Generated by Django 4.1 on 2022-11-22 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_mywatchlistitem_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='release_date',
            field=models.DateField(),
        ),
    ]
